# Generated by Django 3.1.3 on 2020-12-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('info', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aLowerBound', models.IntegerField()),
                ('bLowerBound', models.IntegerField()),
                ('cLowerBound', models.IntegerField()),
                ('dLowerBound', models.IntegerField()),
                ('fLowerBound', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('access', models.CharField(max_length=1)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNum', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('officeHours', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.course')),
                ('gradingScale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.gradingscale')),
            ],
        ),
        migrations.CreateModel(
            name='WeightedAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarDate', models.DateField()),
                ('calendarTopic', models.CharField(max_length=20)),
                ('calendarActivity', models.CharField(max_length=300)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.syllabus')),
            ],
        ),
    ]
