# Generated by Django 3.1.3 on 2020-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
