# Generated by Django 3.1.3 on 2020-12-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='teachingAssistant',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='office',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='officeHours',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(),
        ),
    ]
