# Generated by Django 3.1.3 on 2020-12-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='teachingAssistant',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.section'),
            preserve_default=False,
        ),
    ]
