# Generated by Django 3.1.3 on 2020-12-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0002_auto_20201210_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aLowerBound', models.IntegerField()),
                ('bLowerBound', models.IntegerField()),
                ('cLowerBound', models.IntegerField()),
                ('dLowerBound', models.IntegerField()),
                ('fLowerBound', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.course')),
                ('gradingScale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.gradingscale')),
            ],
        ),
        migrations.CreateModel(
            name='WeightedAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarDate', models.DateField()),
                ('calendarTopic', models.CharField(max_length=20)),
                ('calendarActivity', models.CharField(max_length=300)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.syllabus')),
            ],
        ),
    ]
