# Generated by Django 3.1.3 on 2020-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0002_auto_20201124_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
