# Generated by Django 3.1.3 on 2020-12-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0002_auto_20201216_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='policy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='officeHours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='gradingScale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.gradingscale'),
        ),
    ]
