# Generated by Django 3.1.3 on 2020-12-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0003_auto_20201216_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingscale',
            name='fLowerBound',
        ),
    ]
