# Generated by Django 3.1.3 on 2020-12-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0003_auto_20201206_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.myuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(),
        ),
    ]
