# Generated by Django 3.1.3 on 2020-11-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0003_auto_20201124_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='login',
            new_name='Login',
        ),
    ]
