# Generated by Django 3.1.3 on 2020-12-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0004_auto_20201208_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='syllabus_maker.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(),
        ),
    ]
