# Generated by Django 3.1.3 on 2020-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0004_auto_20201124_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Login',
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
