# Generated by Django 3.1.3 on 2020-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_maker', '0007_auto_20201208_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='teachingAssistant',
            new_name='teacher',
        ),
    ]
